name = "ammobin_nuxt_v3"
type = "javascript"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-10-15"

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = "NITRO_PRESET=cloudflare npm run build"
upload.format = "service-worker"

[env.test]
name = "ammobin-new"
